# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build for macOS

on:
  workflow_dispatch:

jobs:
  mac_build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: navigate
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      shell: bash
      run: |
        cd /Users/runner/work/libnav/libnav/
        mkdir build
        cd build
    
    - name: build
      run: |
        cmake
        make
